[package]
name = "paymoncoin"
version = "0.1.0"
authors = ["Vladislav <negigic@gmail.com>"]
license = "GPL-3.0"

[dependencies]
rocksdb = "0.8.2"
rust-crypto = "^0.2"
patricia-trie = "0.1.0"
log = "0.3.9"
rand = "0.3.20"
time = "0.1.39"
hashdb = "0.1.1"
ethcore-bigint = "0.2.1"
memorydb = "0.1.1"
secp256k1 = "0.8.1"
threadpool = "1.7.1"
rustc-serialize = "0.3.24"
mio = "0.6.12"
byteorder = "0.3"
env_logger = "0.3.1"
slab = "0.3.0"
nix = "0.10.0"
rlibc = "1.0.0"

[[bin]]
name = "paymoncoin"
path = "src/main.rs"
doc = false

[[bin]]
name = "paymoncoin_client"
path = "src/client.rs"
doc = false