[package]
name = "paymoncoin"
version = "0.1.0"
authors = ["Vladislav <negigic@gmail.com>"]
license = "GPL-3.0"

[dependencies]
rocksdb = "0.9.1"
rust-crypto = "^0.2"
patricia-trie = "0.1.0"
log = "0.3.9"
rand = "0.3.20"
time = "0.1.39"
hashdb = "0.1.1"
ethcore-bigint = "0.2.1"
memorydb = "0.1.1"
threadpool = "1.7.1"
rustc-serialize = "0.3.24"
mio = "0.6.13"
byteorder = "0.3"
env_logger = "0.3.1"
ntrumls-plus = "0.0.3"
slab = "0.3.0"
nix = "0.10.0"
libc = "0.2.36"
rlibc = "1.0.0"
lazy_static = "1.0"

[[bin]]
name = "paymoncoin"
path = "src/main.rs"
doc = false
debug = true